name: Clear Dotenv File

on:
  push:
  pull_request:

jobs:
  clear-dotenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clear Dotenv File
        run: rm .env
        # run: echo '' > .env